import React from 'react'

const AboutPage = () => {
  return (
    <div>
        <h1 className='text-4xl font-bold text-center mt-20'>About Me</h1>
        <p className='text-gray-500 text-2xl mt-5'>I am a software designer and developer with a passion for creating innovative solutions to complex problems. I am a quick learner and always looking for new challenges to tackle.</p>
        <p className="text-lg text-gray-500">
           Hello! I'm [Your Name], a passionate developer with a love for creating web applications.
           I have experience in [Your Skills/Technologies]. In my free time, I enjoy [Your Hobbies].
         </p>
         <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsam qui mollitia at, sint aspernatur unde optio. Quis officiis quaerat dolorem recusandae soluta quod sapiente eum quae doloribus dolore? Ad, pariatur.
         Beatae minus voluptas officia cupiditate sequi aliquam voluptates dignissimos, obcaecati eaque provident perspiciatis error aliquid. Illo, earum atque excepturi molestias necessitatibus sapiente nam libero. Quos laborum repellat ipsum molestias mollitia!
         Eveniet placeat aspernatur cum esse praesentium sit ducimus distinctio ullam illo voluptatibus laborum libero vitae et enim saepe, consequatur in illum commodi error sint eius? Quae libero dolorem doloremque aliquam.
         A architecto nobis esse dolorem ipsa commodi laudantium. Quod nobis neque, velit recusandae optio dolores, officia culpa dignissimos repudiandae nemo sed, iure assumenda. Architecto, ea. Atque corporis soluta qui iusto?
         Quod vitae cupiditate in adipisci. Omnis cum sapiente minus. Placeat nisi dicta, quos voluptates facere consequatur dolorem quasi. Sit sapiente fuga voluptas? Sint est cupiditate quos! Autem doloribus alias quo?
         Debitis obcaecati blanditiis vero cumque at ea illo nulla quod iste amet molestias qui, nihil enim numquam adipisci. Rem, officiis? Id vitae fuga vel reiciendis at consequuntur a aliquid reprehenderit.
         In soluta mollitia sunt porro sapiente ut placeat accusamus nihil consequatur voluptatem explicabo quaerat obcaecati consequuntur, asperiores voluptate quas delectus molestiae repudiandae, sit deserunt molestias officiis! Consectetur eaque saepe minima?
         Libero quidem beatae saepe cum magni ex assumenda ab itaque! Facilis, culpa blanditiis! Architecto quis aliquid voluptas! Praesentium error maxime reprehenderit! Ducimus, earum! Velit, debitis necessitatibus animi veniam ad cumque?
         Voluptatum perspiciatis, explicabo, soluta repellendus voluptate vel aperiam illum labore architecto, velit saepe quod. Ducimus nostrum accusamus, voluptatum, possimus delectus perferendis sapiente aut consequuntur incidunt quis accusantium, amet facilis quibusdam!
         Molestiae nisi nam optio animi reiciendis eligendi amet quia reprehenderit, neque, aut odio velit pariatur laudantium exercitationem alias quis dolor tempore quos consectetur nihil qui tempora porro dicta! Exercitationem, et?
         Eum velit nostrum delectus incidunt nemo est, deleniti eligendi nobis tenetur ad praesentium, asperiores dolorem quam doloribus iusto, quos quo necessitatibus magnam sed! Distinctio doloribus optio magni quidem aspernatur temporibus!
         Temporibus debitis tenetur maxime sunt explicabo cumque labore praesentium aut qui, obcaecati itaque ad illum nisi dolores perspiciatis doloribus iure quisquam, reprehenderit nemo reiciendis rem omnis hic! Molestiae, eum ipsam.
         Fuga inventore ea placeat harum veniam molestiae repellat, nemo ab recusandae possimus porro explicabo ut, consectetur ipsum et maiores dolores amet? Reprehenderit assumenda maxime fugit ad odio! Maxime, reprehenderit pariatur!
         Porro quos eaque deserunt eius architecto doloremque debitis, quisquam, id, amet magnam similique. Molestias veniam amet necessitatibus consequuntur accusamus architecto beatae dolores magnam, hic non ex quia voluptatibus itaque vel?
         Repudiandae aliquam officia commodi molestias ab inventore! Numquam corporis ad in libero tenetur suscipit error id nisi! Quo porro reiciendis ullam rerum, amet, non tempora vel quidem assumenda veritatis minus!
         Eius vero illo sit corporis voluptate fuga, maxime rem itaque ab nobis nesciunt natus corrupti sint officiis earum id atque necessitatibus aliquam! Repellat a eaque illum voluptates blanditiis eos exercitationem.
         At, eaque incidunt. Hic, beatae illo quaerat, vero accusamus adipisci deleniti, quas voluptate quam ipsa voluptatibus et eveniet dicta incidunt nihil pariatur! Pariatur consequatur sequi distinctio ullam rem ducimus dolorem?
         Nihil animi asperiores quae. Asperiores dolorem repellendus, dolores ea magni suscipit tempora cumque! Ipsum nisi dignissimos qui suscipit voluptatem rem excepturi delectus quibusdam in, blanditiis quod odio minima? Mollitia, nulla.
         Maiores vero laborum quae deserunt eum tempora, repellendus cumque vel est aperiam commodi animi laudantium rerum molestiae omnis sed dignissimos voluptatem quisquam ad possimus tenetur hic? Quaerat illum vero ut.
         Hic quod natus ea earum doloremque. Voluptate nobis, earum vero asperiores aperiam omnis possimus debitis minus sed tenetur minima rem quod voluptatem officiis a dignissimos? Totam debitis atque nobis velit.
         Rem accusantium labore a sunt magni ratione, eaque itaque voluptas dignissimos dolorum aliquid inventore non eius earum laborum necessitatibus deleniti cumque cum, asperiores mollitia ducimus ut? Veniam ullam quis dolorem?
         Velit eos nostrum nihil blanditiis, excepturi explicabo praesentium autem nam molestiae rerum labore optio. Fugiat quibusdam rem et sed, doloribus, voluptatum perspiciatis, dolores eaque earum ratione libero doloremque impedit! Obcaecati.
         Quisquam sed, dolorem accusantium perspiciatis minus nulla in, sit vitae laborum itaque dicta! Sequi iure eius esse vitae ipsum enim nihil deserunt, dolores saepe, in natus necessitatibus? Corrupti, exercitationem dolor.
         Labore impedit itaque quod dolor ducimus quia doloribus inventore consectetur enim ex, aliquid voluptatibus. Dignissimos provident quasi molestias similique, excepturi distinctio eos nemo saepe, praesentium repellendus itaque dolorum? Ipsam, architecto.
         Veritatis, reiciendis. Non quisquam temporibus consequatur neque perspiciatis consequuntur ab architecto? Aliquid repudiandae fugiat eum excepturi dolore at maiores? Voluptatum eos cum optio natus alias libero eum tenetur nihil! Blanditiis.
         Obcaecati impedit quidem alias, velit sed eaque quisquam corrupti nostrum unde voluptatem ipsum vel amet culpa expedita rerum, sit fugit neque laboriosam recusandae distinctio magnam. Ex dolorem est dignissimos consequatur?
         Ad at magni quia quasi optio est assumenda nisi vitae rem doloremque ipsa cupiditate debitis, veniam alias praesentium, quae consequuntur aperiam, sed quo. Ad hic impedit ex a odio ipsa!
         Ad ipsa nulla nemo. Ipsam, pariatur. Tenetur impedit ducimus quae perspiciatis repellendus voluptatem illo aliquid quaerat, sequi et vel minus est quis, tempore enim molestias expedita voluptas adipisci libero eligendi.
         Nisi aliquam sapiente modi optio, quod magnam laboriosam error molestiae ea atque doloribus beatae exercitationem adipisci, iste quisquam eligendi, dolores et obcaecati quibusdam. Unde, ratione veritatis. Corrupti accusamus expedita natus.
         Corrupti harum quasi a rerum quo accusantium rem autem suscipit necessitatibus beatae aut quia ducimus molestiae cupiditate possimus, repellat aperiam placeat eveniet fuga enim. Modi id sit sunt saepe possimus.
         Aliquid, assumenda facere odit praesentium, officia corporis similique dolor ipsam eaque minus quia, consequatur fugit unde quis! Quibusdam perspiciatis harum pariatur? Quae aliquid ea minima, ad explicabo saepe enim earum.
         Quaerat explicabo laboriosam tempore, accusantium laudantium a porro natus inventore velit, mollitia voluptatibus eos suscipit hic dolorem ipsa? Error quas quidem facere at vero, amet soluta rerum facilis nostrum libero?
         Earum voluptatibus sunt, corrupti officiis, fugiat soluta adipisci asperiores ratione aliquam mollitia sapiente quo, laborum tempore est nobis dolorum nulla enim omnis laboriosam beatae dolor amet alias. Assumenda, voluptates suscipit?
         Doloribus commodi deserunt ratione culpa atque alias? Magni dolorem deleniti laboriosam facere alias accusantium, explicabo, illo optio molestiae soluta eius mollitia voluptatibus, nihil dicta animi est fugiat ad quaerat. Soluta!
         Quasi rerum asperiores tenetur sapiente, esse ex cum quo, eum ipsum eius explicabo eveniet necessitatibus, tempore obcaecati repellat pariatur odio in magni repudiandae culpa sint debitis nobis voluptatibus. Asperiores, enim.
         Et, nulla esse saepe temporibus perferendis qui inventore. Blanditiis architecto quas quibusdam voluptatibus, id quia labore animi minus quo tenetur fugit temporibus deserunt unde qui ipsum cupiditate porro suscipit eius.
         Nam ratione ducimus asperiores laboriosam neque? Deleniti temporibus dolorem architecto aliquam corporis repellendus, numquam consequatur possimus ad nesciunt magni recusandae quas quibusdam quod ipsam necessitatibus praesentium eius non fugit quia.
         Molestiae pariatur necessitatibus quisquam ex incidunt cum nostrum quibusdam consectetur fuga temporibus eveniet, est qui ipsam accusantium dignissimos quo magnam laboriosam veniam nam accusamus consequuntur beatae iusto. Alias, enim sed!
         Quis dolorum numquam odio inventore beatae illum molestiae asperiores nesciunt delectus non magni, maxime enim, id ipsam rerum dolore perferendis! Quidem fugit, officiis dignissimos porro alias sapiente neque numquam voluptatum!
         Accusamus repellat, ipsam, autem dignissimos, nemo magnam fuga repellendus facere quae consequuntur temporibus. Sit culpa ipsa eveniet consectetur veniam ad doloribus quidem, officiis molestias accusamus rem atque amet? Eum, voluptate.
         Sapiente amet iusto, sunt nihil cupiditate qui nam quisquam perferendis expedita dignissimos neque officia deserunt ex cumque dolores modi illo veritatis minima nesciunt. Explicabo, pariatur eos inventore amet laboriosam delectus?
         Neque, quia repellat? Rem fuga explicabo necessitatibus numquam perspiciatis aliquam eaque, nobis repudiandae quas impedit delectus, sed amet sint. Sit saepe nisi architecto culpa officiis necessitatibus veritatis reiciendis molestiae placeat?
         Sunt voluptatibus nihil ad maiores necessitatibus nemo dolore nam veritatis ut molestiae ab inventore optio, totam, at obcaecati suscipit explicabo facilis, delectus autem. Dolorum facere est autem ut eos sunt.
         In accusamus, quae explicabo iusto inventore voluptatum consectetur aut pariatur odit ab at maiores vel incidunt perferendis laboriosam fugit rem, totam odio? Voluptatem quisquam dolor sed esse, commodi voluptates quae?
         Excepturi magnam ab veritatis numquam impedit quos et adipisci porro, minima ullam fuga. Modi, veniam beatae. Quaerat repudiandae expedita veniam alias deleniti animi, unde voluptas perferendis, nesciunt sequi quis sint?
         Laudantium, dolor sunt. Amet id fugiat ipsam animi minima porro laborum, sed inventore eos nihil. Quos repudiandae neque, praesentium quod quam itaque quidem asperiores ea iure nihil totam doloribus voluptatibus?
         Facere maxime debitis eveniet ab exercitationem quaerat dolores. Mollitia, nemo unde voluptatibus iure labore error quisquam! Culpa perferendis esse ducimus atque consequatur nobis deleniti, quas impedit veritatis, a reiciendis voluptatem?
         Hic vitae architecto perferendis sapiente sequi illo est amet sed, placeat explicabo. Cum hic eum, nobis maxime placeat quos praesentium consequuntur laborum laudantium temporibus ex, officia, ut harum repellendus non!
         Non qui voluptates, sapiente nihil nam temporibus sint natus quia ut ducimus dignissimos numquam sunt a quos minus, optio illo libero asperiores. Officiis iure quos voluptates debitis, in blanditiis unde.
         Quia, sed. Blanditiis mollitia nam quis tempore officiis sed necessitatibus accusantium at exercitationem illum sit quibusdam dolores quos placeat, error iusto obcaecati doloremque inventore voluptas doloribus, facere consequuntur? Laboriosam, molestias.
         Nesciunt iusto officiis necessitatibus est nam voluptate dolore. In, consectetur repudiandae. Natus nemo sequi minus id expedita architecto, necessitatibus ullam illo accusamus voluptates adipisci et, quam molestiae molestias ad nulla.
         Sit eligendi nam doloremque qui sed numquam cupiditate vitae sequi quibusdam eum, harum possimus incidunt dicta suscipit necessitatibus dolor modi aspernatur ratione molestiae provident reiciendis totam aliquam! Voluptate, vel dolor!
         Aspernatur dolores repellat, eum rem sit quae illum pariatur excepturi quos maiores autem id consequuntur ipsam iure sed error eligendi earum debitis sapiente qui ducimus, est aut! Dolor, impedit voluptas!
         Aliquam commodi culpa porro voluptatibus, nam quo obcaecati accusamus officiis quia molestiae alias natus iure sapiente ullam, exercitationem, vitae rem. Incidunt esse quas consequatur magni tempore ex illo, vitae aliquam?
         Reprehenderit tempore cumque at exercitationem possimus nesciunt tenetur accusamus fuga voluptates, obcaecati ipsam quia harum quisquam culpa hic quo aliquid minus autem ea earum iusto, vel doloremque sapiente voluptatum. Eos?
         Similique consequuntur tenetur rem iusto accusantium optio! Tenetur quam excepturi velit assumenda autem ducimus deserunt blanditiis id! Vel laudantium doloribus nobis saepe quas voluptatem, autem quae consectetur veniam accusantium dolore?
         Possimus id quidem voluptatum! Ullam eum architecto exercitationem saepe molestiae possimus amet maxime nemo aspernatur in fugiat consectetur repellat veritatis sequi provident repellendus, perferendis dolores. Iure repellendus quia tempore incidunt.
         Enim, odit cupiditate amet hic blanditiis vero id laborum facilis sit eius beatae provident molestiae a ex in quia sed recusandae labore illum incidunt mollitia iusto voluptatibus quibusdam. Natus, nesciunt.
         Maxime, error obcaecati doloribus officiis distinctio illo porro velit veniam natus eaque dolorem, assumenda totam voluptas vero adipisci impedit maiores ipsam ullam? Dolore impedit necessitatibus tempora ex quae. Officia, quam.
         Voluptatum id dolores quidem distinctio quos itaque nihil provident nisi nemo quam, adipisci inventore ut ullam! Assumenda sequi cum consequatur, architecto doloribus, accusantium minima veniam ex provident sunt inventore facilis!
         Neque aliquid doloremque eos, recusandae vel molestias beatae minima reiciendis necessitatibus! Numquam iure porro nostrum nemo autem! Maiores natus sed ex nobis aut reiciendis minus, quam nemo saepe excepturi pariatur.
         Officiis nihil voluptatem iste officia? Delectus odio similique qui, sint natus dolorem laborum sed totam. Saepe repudiandae laudantium beatae itaque, magni ipsum suscipit facere nesciunt, omnis animi error tempora inventore.
         Totam eum iure dignissimos, alias similique quaerat a architecto laborum accusantium veniam sit ex. Inventore rem quia at veritatis delectus ab. Officia assumenda id ducimus voluptas odit voluptate accusamus nesciunt.
         Saepe neque non atque est quod voluptatibus, voluptate ut nobis illum a iure, deserunt quo. Ipsum neque fugiat, at quos inventore voluptatem eius excepturi nulla repellat aperiam, similique, ullam necessitatibus.
         Libero ea voluptate, perspiciatis qui quo porro in amet! Quos reprehenderit omnis quia voluptatibus enim, repellat quis repellendus illum, aliquid, placeat praesentium maiores? Quod vel deleniti perferendis natus possimus eveniet!
         Consectetur ex adipisci ullam rem eveniet ab ipsum quaerat illum, repellat iure eius maxime blanditiis libero? Itaque voluptas consectetur quasi illo quia voluptate aperiam ut quis possimus vero. Veniam, ipsam!
         Magnam voluptate praesentium eos reiciendis molestias, alias unde consectetur repudiandae quas delectus fugiat tenetur ad ipsum reprehenderit magni, iste nam voluptatibus optio necessitatibus laudantium nobis? Dignissimos facere aliquid tempore doloribus?
         Aspernatur qui repellat labore deleniti dicta praesentium error atque quidem, laboriosam suscipit, iusto, magnam placeat? Sequi commodi nemo ipsa perferendis dolorem dolor corrupti eum error, explicabo, maxime ducimus ratione ex!
         Qui error repellendus rem voluptatum commodi, saepe obcaecati nobis architecto ab placeat vero consequuntur eaque iusto dolorem totam quisquam officia quidem eveniet cum. Assumenda modi nemo molestiae voluptates, tempora dolorem?
         Fuga, omnis odio. Mollitia possimus consectetur maiores accusamus, doloremque officia ea sunt omnis molestias exercitationem quas autem ducimus ipsam, veritatis voluptas earum aut delectus esse illo unde rem. Ratione, rerum!
         Libero suscipit adipisci minima, laudantium odio odit voluptate sed ipsa nihil, quibusdam saepe at ut sunt est. Ullam, voluptates sequi molestias, at consequatur quas accusamus accusantium commodi aspernatur obcaecati fugiat!
         Excepturi nam iste, veritatis asperiores earum officiis provident laborum odit voluptatibus. Fuga totam tempore, adipisci expedita vitae vero quis at architecto consequuntur neque labore, quasi, vel alias? Molestias, reiciendis quae.
         Autem suscipit ratione quis possimus soluta quo illum unde ipsa a, molestias esse. Molestiae autem quos labore aut quibusdam non, beatae atque aliquam pariatur deleniti fugiat ad reiciendis voluptates nam.
         Iure, sunt esse, nihil obcaecati ut assumenda cupiditate at qui iusto cum ab necessitatibus deserunt sint aliquam quasi excepturi impedit earum natus voluptates amet, adipisci nobis alias. Architecto, soluta voluptatibus!
         Eveniet alias aut aliquam excepturi dicta consequatur doloremque totam amet, modi culpa quas aliquid repellat nesciunt facilis nulla distinctio vero quisquam quasi sed impedit fuga! Autem, earum. Consectetur, et rem.
         Voluptates voluptatum sint doloremque iure alias tempore at mollitia quasi, consequuntur animi corrupti dolorem beatae, a quos facere ut hic necessitatibus aperiam minima tempora sit! Voluptatum illo repellat dolore. Nesciunt.
         Libero aut dolor laudantium quo molestias nostrum nesciunt incidunt et nemo eum, ipsa at veniam possimus reiciendis necessitatibus, perspiciatis modi aperiam. Earum nihil temporibus itaque fugiat aut, saepe ad vero!
         Aliquam fugiat harum numquam deleniti, ipsum tempora placeat iusto veritatis! Ab architecto, est corporis cum dignissimos laboriosam soluta nihil temporibus ducimus modi, esse quod tempore doloremque eveniet omnis quasi a?
         Iusto, iste tempore. Veritatis incidunt inventore velit, tempore ipsum consectetur temporibus laboriosam consequatur quisquam aut cupiditate placeat at eius iure quasi repudiandae recusandae, tenetur ea, tempora pariatur voluptatum alias. Maxime!
         Rerum, ipsum libero. Dolor rerum quidem, fuga hic minus iure consequuntur repellat earum quod harum perferendis impedit eius eum sint accusantium explicabo vero esse reiciendis delectus officia sed aut ipsum.
         Exercitationem illum cumque optio, deleniti eaque vel repudiandae. Reiciendis impedit labore ab enim. Architecto dignissimos dolor saepe cum sapiente sunt nulla cupiditate consectetur! Necessitatibus officia cum pariatur fugiat aut magni?
         Sit aliquid nam provident cumque vitae tempore perferendis, voluptatem quo quam? Delectus ipsam labore placeat iure voluptatibus a consequuntur eum in dolorum nesciunt libero magni aspernatur, sint alias ea reiciendis.
         Unde sed facere laudantium culpa modi, voluptatum totam, voluptates cupiditate asperiores soluta veniam iure dolores, esse sit quaerat necessitatibus quos? Pariatur architecto itaque ex tempore rerum expedita, atque eligendi amet!
         Necessitatibus maxime quae molestias sed omnis earum eos illum repellat, dolorem inventore laudantium culpa tempore est. Repudiandae accusamus quasi earum obcaecati adipisci facere ad esse quidem dicta voluptas, eos sit.
         Similique enim, quasi, doloremque earum perferendis vitae alias veritatis quidem nihil facere distinctio molestias doloribus, maxime asperiores! Facere, culpa recusandae error quidem odit ullam quod ex eos, quas illo nobis?
         Aperiam ex necessitatibus repellendus modi? Sequi, iusto eligendi dolor recusandae esse vitae veniam, cupiditate similique quidem distinctio quod illo numquam, rem deleniti? Accusamus recusandae itaque nihil expedita, nobis numquam atque.
         Quam, quisquam placeat! Amet magni suscipit aperiam mollitia quia, modi, adipisci maxime beatae velit rerum a placeat incidunt, eaque omnis nam sapiente reiciendis voluptas pariatur? Assumenda pariatur perspiciatis nostrum id!
         Praesentium culpa accusamus enim, natus id error exercitationem? Rerum cum earum qui perspiciatis suscipit quod accusantium aut maiores non dolore. Excepturi quo nulla aspernatur minima magnam non corrupti quasi est.
         Omnis, deleniti mollitia. Architecto, minima? Vero exercitationem dolores officiis ullam sint cupiditate voluptatibus eum harum odio voluptas. Optio qui consectetur facilis dignissimos labore inventore magni accusamus, quasi quaerat, id ad.
         Quam laudantium illo error sit earum facilis facere odit vero exercitationem. Ad eligendi illum labore quos sunt, ea dignissimos, earum asperiores eaque blanditiis corrupti porro, incidunt molestiae modi! Doloremque, porro.
         Vel ea fugit quae nesciunt! Vitae neque consectetur numquam at ex repellendus voluptatibus tempora quam eligendi nesciunt fuga animi laborum aspernatur, dolor molestias sed beatae! Laborum dignissimos voluptatem magni delectus.
         Porro non commodi voluptate, quidem animi explicabo praesentium facilis incidunt blanditiis alias neque sint laborum, distinctio ex nam. Fuga, vero? Corporis recusandae ab consectetur qui. Corporis sint placeat fuga nulla.
         Alias libero quibusdam aliquam aut sunt ullam, non tempora cumque recusandae. Blanditiis, dolores maxime saepe deleniti qui facere. A perspiciatis quam velit distinctio libero quia atque accusantium quae quod cum.
         Earum distinctio vero sequi ab fugit quidem, nulla assumenda suscipit maiores, error non id voluptatem fuga! Voluptates, ipsum quo assumenda tempore doloribus quos? Minus nobis consequuntur suscipit, alias sequi ipsum?
         Vel reiciendis sit illo possimus ipsa doloremque voluptates aliquam excepturi adipisci delectus error cumque, tempore ullam quae alias doloribus eius sunt quis cum ut labore. Vitae, ab? Impedit, soluta minus!
         Libero sequi debitis, illum fugit recusandae excepturi fugiat eaque nulla? Voluptates autem possimus libero debitis maiores. Veniam, autem. Voluptate nobis, molestias nisi vel unde veniam culpa asperiores quis cum. Libero!
         Laudantium non libero error, quaerat ullam consequatur ipsum quasi doloremque, nam perferendis harum possimus sequi assumenda iste ipsam delectus magnam aliquam accusantium consectetur tempore molestiae cum perspiciatis tempora. Numquam, quasi?
         Laboriosam blanditiis in corporis, aut excepturi rem animi temporibus eveniet porro hic culpa, aliquid inventore? Veritatis dolorum recusandae eum, quibusdam ab perferendis illum hic doloribus ullam ipsam? Neque, culpa vel.
         Inventore eaque non fuga, fugiat incidunt, iure mollitia adipisci excepturi aut eum repellat. Facilis vel ullam iure ratione accusamus? Perferendis aliquam vero nemo ad. Quo similique ullam adipisci tenetur praesentium.
         Blanditiis velit officia perspiciatis alias eius voluptatum reiciendis beatae suscipit maiores quo. Cupiditate vero quidem quas ab quaerat voluptatibus, perferendis necessitatibus molestiae architecto accusantium quae rerum? Officia amet impedit eos.</p>
    </div>
  )
}

export default AboutPage;